### ISSUE TITLE
DApp Testing

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#15]
Based on the planning on https://github.com/cardanoapi/hardfork-testing/issues/14, implement the Scenarios for dapp testing.

### Todos
- [x] Review https://github.com/dQuadrant/cardano-marketplace for and the vasil benchmarks performed.
- [x] Prepare Kuber haskell library for dApp testing.
- [x] Implement scenarios for testing

### Acceptance Criteria
-  [x] `cardnao-marketplace` repo is updated with the test scenarios implemented with PlutusV3
-  [ ] Performance report or blog how new v3 features improves the performance and or transaction size/fees
