### ISSUE TITLE
[Planning] Guardrails Testing

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#18]
Guardrails testing - get a list of guardrails, when we reach end of April  and mainnet candidate - we test x50 guardrails with different permutations

Test harness from Dev to Production
Made by Ziyang
### TODO
- [x] Review cardano-constitution module on plutus repo
- [x] Compile and build script and script hash to use for testing guardrails
- [x] Prepare a new test namely test_guardrails create a new constitution using plutus script 
- [x] Verify cardano-cli supports constitution using plutus script
- [x] Verify cardano-cluster-lib has added cli commands
- [x] Prepare a proposal param update gov action after the constitution script has been enacted
- [x] Prepare a workaround for transaction build command with the support of proposal-script

### Acceptance Criteria
- [x] Discover the tools, related repos/tests and decide on them
- [x] Planning checklist on list of all tests available, their results and the new tests to add.
