### ISSUE TITLE
Reporting Dashboard for hardfork testing

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#24]
### ToDos
Review Current result dashboard at: https://tests.cardano.intersectmbo.org/
Review Test reports generated in our tests and come up with a way to visualize them or integrate them to the reporting dashboard.

### Acceptance criteria
- [x] Script or instruction to visualize our current test reports.
- [x] Proposal on way to integrate it into the tests.cardano.intersectmobo.org --> PR to `cardano-test-plans` repo and tests on `cardano-node-tests`
- [x] Integrate relevant tests to `cardano-node-tests` and reflect the results on tests dashboard

**Comment by spannercode** [comment]
The tests to be added on cardano-node-tests and which are to be updated on the test results dashboard are already covered. This is considered complete from our side.
