### ISSUE TITLE
[Milestone 01] Update Cardano Test plans dashboard.

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#7]
Include test reports generated from following work into the Test Plan dashboard
- [x] https://github.com/cardanoapi/hardfork-testing/issues/2
- [x] https://github.com/cardanoapi/hardfork-testing/issues/3
- [x] https://github.com/cardanoapi/hardfork-testing/issues/4
- [x] https://github.com/cardanoapi/hardfork-testing/issues/5

**Comment by spannercode** [comment]
The blocker is resolved with publication of self hosted test results (https://cardanoapi.github.io/gov-action-load-testing)
- https://github.com/cardanoapi/hardfork-testing/issues/24
