### ISSUE TITLE
Software/Hardware Wallet validation

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#8]
**To Discover**
- [x] Prepare a plan to test different software wallets and hardware wallet
- [x] Signing Tests, other functionality tests.

Validate hardfork readiness for following wallets
**Soft Wallet** (YOROI, Nami, Flint, Cardano Wallet(HAL, Adresita - David Clarke))
- [x] Yoroi
- [x] Nami
- [ ] ~Flint~
- [x] Eternl
- [ ] ~Typhon~
 

**Hardware Wallet**
- [x] Check with Vacuumlabs for Hardware wallets validation (Ryan Williams as contact)

### Acceptance Criteria
- [x] Planning document (which wallets and what tests are in scope)
- [x] Report of the implemented wallet tests and their results

**Comment by mesudip** [comment]
### Scope
- Supports the cip-95 extension for `enable` function
- Transaction signing with txs containing PlutusV3
- Signing Voting related transactions.
- Signing Registration/Delegation certificate related transactions.

### How
- Update kuber docs for new features. https://kuberide.com/kuber/docs/tutorials/intro/
- Prepare list of transaction types to test.
- Use KuberIDE to test the transactions.


### ToDO: 
- [x] List the transactions types to be tested.
- [x] Prepare a report template including all the transaction type and the results for each wallet.
- [x] Obtain results and fill the report for all the wallets

**Comment by spannercode** [comment]
The reporting is done via this Google sheet document:
https://docs.google.com/spreadsheets/d/1Vwr2Ox8uCehf_OCvmYoeTItLkxtW2GaGKXMj8vZSrG8/edit?usp=sharing

It is already shared with some Intersect members including Ryan and Hard fork Intersect/IOG slack team.

**Comment by spannercode** [comment]
@nabinpkl lets consider Flint and Typhoon as well and add to the sheet.
@reeshavacharya Lets do hardware wallet tests this week.

**Comment by spannercode** [comment]
This completes the hardware tests
https://github.com/cardanoapi/hardfork-testing/issues/42
