### ISSUE TITLE
Ledger API testing

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#9]
### ToDos
- [x] Check existing ledger api tests, what is covered and what is not
- [x] Add tests of functionalities that are not covered.

### Acceptance Criteria
- [x] Planning document listing new tests to add on top of existing tests
- [ ] Report on the new tests and verification of the existing tests, and their correctness (PR merge remaining)
